server:
  port: 8081
spring:
  application:
    name: dp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dianping_ms?useSSL=false&serverTimezone=UTC
    username: root
    password: 951753
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.dp.entity # 别名扫描包
logging:
  level:
    com.dp: debug